---
# Create cloud-init files for all VMs

# - name: remove old directory for cloud-init files
#   file: name="{{ cloud_init_dir }}" state=absent

- name: Create directory for cloud-init files
  file: name="{{ cloud_init_dir }}/configdrive-vm-{{ item }}/openstack/latest"
        state=directory
  with_sequence: count={{ vm_count }}

- template: src="{{ cloud_init_profile }}.j2"
            dest="{{ cloud_init_dir }}/configdrive-vm-{{ item }}/openstack/latest/user_data"
  with_sequence: count={{ vm_count }}

- name: set SELinux attributes to cloud-init directory
  file: name="{{ cloud_init_dir }}/configdrive-vm-{{ item }}"
        setype="svirt_image_t" recurse=yes
  with_sequence: count={{ vm_count }}
  when: ansible_selinux.status == "enabled" and ansible_selinux.mode == "enforcing"