---
# Create cloud-init files for all VMs

- include:    new_discovery_token.yml
  when:       discovery_token == "" and request_discovery_token | bool

- include:    create_cloud_init.yml
  sudo:       yes
  vars:
    public_ssh_key:   "{{ lookup('file', home_dir + '/' + my_public_key_file ) }}"
    discovery_url:    "{{ new_discovery_token.content | default( default_discovery_url + '/' + discovery_token ) }}"
