---
# Download PyPy and get-pip

- name: remove old download directory, if exists
  file: name={{ download_dir }} state=absent

- name: create download directory
  file: name={{ download_dir }} state=directory

- name: download PyPy and get-pip
  get_url: dest={{ download_dir }} url="{{ pypy_download_url }}"
  with_items:
    - pypy_download_url
    - get_pip_download_url

- name: create symlinks to PyPy and get-pip