---

- name: Copy zookeeper service systemd file
  sudo: yes
  command: cp "{{ zookeeper_conf_host_dir }}/zookeeper.service"
           /etc/systemd/system/zookeeper.service

- name: Enable zookeeper service
  sudo: yes
  service: name=zookeeper state=stopped enabled=yes

- name: Reload systemd
  sudo: yes
  command: systemctl daemon-reload

- name: Restart zookeeper service
  sudo: yes
  service: name=zookeeper state=restarted
