---
# Deploy Docker zookeeper container 

- name: Copy zookeeper systemd file
  template: src="systemd-zookeeper.j2" dest=/etc/systemd/system
  notify:
    - Enable zookeeper service

# ---------------------------------------------------------------------
#  Configuration 
# ---------------------------------------------------------------------

- name: Create folder for zookeper configuration
  file: path="{{ zookeeper_conf_dir}" state=directory

- name: Create configuration files
  template: src={{ item }} dest="{{ zookeeper_conf_dir}}/{{ item | replace('.j2', '') }}" backup=yes
  with_items:
    - zoo.cfg.j2
    - log4j.properties.j2
    - myid.j2
  notify:
    - Restart zookeeper service
