---
# Deploy Docker zookeeper container 

# ---------------------------------------------------------------------
#  Service 
# ---------------------------------------------------------------------

- name: Create folder for zookeeper configuration, data and log files
  file: path="{{ item }}" state=directory
  with_items:
    - "{{ zookeeper_conf_host_dir }}"
    - "{{ zookeeper_volume_host_dir }}/data"
    - "{{ zookeeper_volume_host_dir }}/log"

- name: Create systemd service file
  template: src={{ item }} dest="{{ zookeeper_conf_host_dir }}/{{ item | replace('.j2', '') }}"
  with_items:
    - zookeeper.service.j2
  notify:
    - Copy zookeeper service systemd file
    - Enable zookeeper service
    - Restart zookeeper service

# ---------------------------------------------------------------------
#  Configuration 
# ---------------------------------------------------------------------

- name: Create configuration files
  template: src={{ item }} dest="{{ zookeeper_conf_host_dir }}/{{ item | replace('.j2', '') }}"
            backup=yes
  with_items:
    - zoo.cfg.j2
    - log4j.properties.j2
    - myid.j2
  notify:
    - Restart zookeeper service

- name: Create link to myid file
  file: src="{{ zookeeper_conf_container_dir }}/{{ item }}"
        dest="{{ zookeeper_volume_host_dir }}/data/{{ item }}"
        state=link
        force=yes
  with_items:
    - myid
