---
# --------------------------------------------------------------------------
#      Ansible playbook to set up Ruby on Rails development environment
# --------------------------------------------------------------------------

- hosts: ruby-dev
  gather_facts: no

  roles:
    - { role: min-install,      when: do_min_install }

- hosts: ruby-dev

  roles:
    - { role: ruby-dev-env,     tags: ruby    }
    - { role: sublime-text,     tags: sublime }
