# -*- mode: ruby -*-
# vi: set ft=ruby :

# ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|

  config.vm.box      = "generic/ubuntu1804"
  config.vm.hostname = "golang"

	# define vm params
  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus     = 2
    libvirt.memory   = 4096

    libvirt.storage_pool_name = "HDD-2-fs"
  end

  # Install Go
  config.vm.provision "shell" do |shell|
    shell.path = "go-install.sh"
  end

end
