---

- name: Copy marathon service systemd file
  sudo: yes
  command: cp "{{ marathon_host_dir }}/marathon.service"
           /etc/systemd/system/marathon.service

- name: Enable marathon service
  sudo: yes
  service: name=marathon state=stopped enabled=yes

- name: Reload systemd
  sudo: yes
  command: systemctl daemon-reload

- name: Restart marathon service
  sudo: yes
  service: name=marathon state=restarted
