---
# Install PyPy and get-pip to CoreOS servers

- name: copy PyPy to all servers
  connection: local
  command: rsync -avz
              "{{ download_dir }}/{{ pypy_tarball }}"
              "{{ coreos_username }}@{{ inventory_hostname }}:"

- name: install PyPy
  script: install_python.sh
