---
# Install PyPy to CoreOS servers

- name: check if python is already installed
  raw: stat {{ python_bin_location }}
  register: need_python
  ignore_errors: True

- include: install_pypy.yml
  when: need_python | failed or force_python_install | bool
