---
# Download and install Docker Compose

# download ----------------------------------------------------

- name: create folder for downloaded files
  connection: local
  run_once: true
  file: path="{{ docker_download_dir }}" state=directory

- name: download docker compose package
  connection: local
  run_once: true
  get_url: url="{{ item.0 }}"
           dest="{{ docker_download_dir }}/{{ item.1 }}"
  with_items:
    - "{{ docker_compose_downloads }}"

# install -----------------------------------------------------

- name: transfer/install docker compose package
  sudo: yes
  copy: src="{{ docker_download_dir }}/{{ item.1 }}"
        dest="{{ item.2 }}"
        mode="u+w,a+rx" owner="root" group="root"
  with_items:
    - "{{ docker_compose_downloads }}"

# cleanup -----------------------------------------------------

# FIXME: this (local) operations seems to create some sort of race condition

- name: remove downloaded package(s) and folder (local)
  connection: local
  run_once: true
  file: name="{{ docker_download_dir }}/{{ item.1 }}" state=absent
  when: keep_local_files == "no"
  with_items:
    - "{{ docker_compose_downloads }}"
