---
# Docker Compose installation

- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "Linux.yml"

- include: install_by_download.yml
  when: download_docker_compose == "yes"

- include: install_with_pip.yml
  when: download_docker_compose != "yes"
