---
# Install Python and other packages required by Ansible

- name: check for Python2
  raw: python2 -V
  register: python2_test
  ignore_errors: true

# test for Fedora and do the installation is positive

- include: install_fedora.yml
  when: python2_test.rc != 0