---
# Install SublimeText

- name: download SublimeText
  get_url: url="{{ sublime_text_url }}/{{ sublime_text_name }}.tar.bz2" dest={{ sublime_text_download_dest }}

- name: extract SublimeText archive file
  sudo: yes
  unarchive: src="{{ sublime_text_download_dest }}/{{ sublime_text_name }}.tar.bz2" dest={{ sublime_text_dest }} copy=no creates="{{ sublime_text_dest }}/{{ sublime_text_extract_dir }}"

- name: remove stale SublimeText directory (only of the directory will have to be renamed)
  sudo: yes
  file: path="{{ sublime_text_dest }}/{{ sublime_text_dir }}" state=absent
  when: sublime_text_extract_dir != sublime_text_dir

- name: rename SublimeText directory (to avoid complications with paths that contain spaces)
  sudo: yes
  command: mv "{{ sublime_text_dest }}/{{ sublime_text_extract_dir }}" "{{ sublime_text_dest }}/{{ sublime_text_dir }}"
  when: sublime_text_extract_dir != sublime_text_dir

- name: update bashrc file (SublimeText2)
  lineinfile: dest="{{ ansible_user_dir }}/.bashrc" line="{{ item }}" state=present insertafter=EOF
  with_items: bashrc_addons

- name: delete downloaded SublimeText archive file
  file: path="{{ sublime_text_download_dest }}/{{ sublime_text_name }}.tar.bz2" state=absent
