---

- name: Copy chronos service systemd file
  sudo: yes
  command: cp "{{ chronos_host_dir }}/chronos.service"
           /etc/systemd/system/chronos.service

- name: Enable chronos service
  sudo: yes
  service: name=chronos state=stopped enabled=yes

- name: Reload systemd
  sudo: yes
  command: systemctl daemon-reload

- name: Restart chronos service
  sudo: yes
  service: name=chronos state=restarted
