---

- name: Enable ssh authorization for sudo
  lineinfile: dest=/etc/pam.d/sudo insertbefore="^auth"
              line="auth sufficient pam_ssh_agent_auth.so file=%h/.ssh/authorized_keys"
              state=present

- name: Install ssh authorization lib (with yum)
  yum: name={{ item }} state=present
  when: ansible_pkg_mgr == "yum"
  with_items: ssh_auth_packages[ ansible_os_family ]

- name: Add APT repository (needed for the subsequent apt-install)
  apt_repository: repo="{{ item }}"
  with_items: ssh_auth_repos
  when: ansible_pkg_mgr == "apt"

- name: Install software packages (with apt)
  apt: name={{ item }} state=latest update_cache=yes
  with_items: ssh_auth_packages[ ansible_os_family ]
  when: ansible_pkg_mgr == "apt"
