---
# Additional customizations of the sudo access

- name: Copy file to sudoers.d
  copy: src={{ item }} dest=/etc/sudoers.d/
  with_items:
    - 50-defaults

- name: Set correct file permissions to new files in sudoers.d/
  file: name=/etc/sudoers.d/{{ item }} mode=600
  with_items:
    - 50-defaults

- name: Enable ssh authorization for sudo
  lineinfile: dest=/etc/pam.d/sudo insertbefore="^auth"
              line="auth sufficient pam_ssh_agent_auth.so file=%h/.ssh/authorized_keys"
              state=present
