---
# Grant sudo

- name: Copy file to sudoers.d
  copy: src={{ item }} dest=/etc/sudoers.d/
  with_items:
    - 50-defaults

- name: Set correct file permissions to new files in sudoers.d/
  file: name=/etc/sudoers.d/{{ item }} mode=600
  with_items:
    - 50-defaults
