---
# Shutdown

- name: shutdown coreos virtual machines
  virt: name="{{ item.key }}"
        command=shutdown
  when: item.key | match("coreos-*") and item.value.state != "shutdown"
  with_dict: vms

- name: make vm-state helper script available
  copy: src=files/vm_state_wait.sh dest=/tmp mode="u+x"

- name: wait for virtual machines to shutdown
  command: /tmp/vm_state_wait.sh -s shut -t {{ vm_shutdown_timeout }} {{ item.key }}
  register: shutdown_result
  when: item.key | match("coreos-*")
  with_dict: vms

# - debug: msg="result = {{ shutdown_result }}"

- set_fact:
    vms_are_shutdown="{{ shutdown_result | vms_in_state }}"

# - debug: msg="all vms are in shutdown state => {{ vms_are_shutdown }}"

# keep the helper script for the next round
- name: remove helper script
  file: name=/tmp/vm_state_wait.sh state=absent
  when: vms_are_shutdown

