---
# ----------------------------------------------------------
#                Administrate cluster of CoreOS VM
# ----------------------------------------------------------

# ----------------------------------------------------------
#  2. Create VMs
# ----------------------------------------------------------

- hosts: provision_host

  pre_tasks:

    - name: get list of all virtual machines
      virt: command=list_vms
      tags: [ 'list', 'status', 'start', 'shutdown', 'restart' ]
      register: virt_vms

    - name: get info of all virtual machines
      virt: command=info
      tags: [ 'info', 'start', 'shutdown', 'restart' ]
      register: virt_info

  tasks:

    - debug: var=virt_vms.list_vms
      tags: list

    - debug: var=virt_info
      tags: info

    - include: tasks/status.yml vms={{ virt_vms.list_vms }}
      tags: status

    - include: tasks/shutdown.yml vms={{ virt_info }}
      tags: [ 'shutdown', 'restart' ]

    - name: get info of all virtual machines (after shutdown command)
      virt: command=info
      tags: restart
      register: virt_info

    - include: tasks/start.yml vms={{ virt_info }}
      tags: [ 'start', 'restart' ]

    # Pause for N seconds to start up all vms
    - pause: seconds={{ vm_startup_pause }}
      tags: [ 'start', 'restart' ]

# ----------------------------------------------------------
# eof
#