---
# ----------------------------------------------------------
#                Administrate cluster of CoreOS VM
# ----------------------------------------------------------

# ----------------------------------------------------------
#  2. Create VMs
# ----------------------------------------------------------

- hosts: provision_host

  pre_tasks:

    - name: get list of all virtual machines
      virt: command=list_vms name="coreos-1"
      tags: [ 'list', 'status', 'start', 'shutdown', 'restart' ]
      register: virt_vms

    - debug: var=virt_vms.list_vms
      tags: list

    - name: get info of all virtual machines
      virt: command=info
      tags: [ 'info', 'start', 'shutdown', 'restart' ]
      register: virt_info

    - debug: var=virt_info
      tags: info

  tasks:

    - include: tasks/status.yml vms={{ virt_vms.list_vms }}
      tags: status

    # this control variable has to be set in advance otherwise
    # the <until> check in the loop of the shutdown task will fail
    - set_fact:
        vms_are_shutdown=true
      tags: [ 'shutdown', 'restart' ]

    - include: tasks/shutdown.yml vms={{ virt_info }}
      tags: [ 'shutdown', 'restart' ]
      until:    vms_are_shutdown
      retries:  3
      delay:    1

    - name: get info of all virtual machines (after shutdown command)
      virt: command=info
      tags: restart
      register: virt_info

    - include: tasks/start.yml vms={{ virt_info }}
      tags: [ 'start', 'restart' ]

    # Pause for N seconds to start up all vms
    - pause: seconds={{ vm_startup_pause }}
      tags: [ 'start', 'restart' ]

# ----------------------------------------------------------
# eof
#