---
# ----------------------------------------------------------
#                Create cluster of CoreOS VMs
# ----------------------------------------------------------

- hosts: 127.0.0.1
  connection: local
  tasks:

    - assert:   { that: "vm_count > 1" }

    - include:  tasks/local_setup.yml

# ----------------------------------------------------------
#  1. Download VM image
# ----------------------------------------------------------

- hosts: download_host
  roles:

    - { role: download_image, tags: download }

# ----------------------------------------------------------
#  2. Create VMs
# ----------------------------------------------------------

- hosts: provision_host

  pre_tasks:

    - name: discover vm image name
      command: cat "{{ local_vm_image_dir }}"/vm_image_name.txt
      tags: disks
      register: saved_vm_image_name

  vars:

    vm_image_name_compressed:   "{{ saved_vm_image_name.stdout }}"
    vm_image_name:              '{{ vm_image_name_compressed | regex_replace(".bz2$", "") }}'

  roles:

    - { role: disk_partition,     tags: disks }
    - { role: cloud_init,         tags: init }
    - { role: virtual_machine,    tags: vms }

# ----------------------------------------------------------
# eof
#