---
# ------------------------------------------------------------------- #
#                     Mesosphere on CoreOS cluster                    #
# ------------------------------------------------------------------- #

- hosts: 127.0.0.1
  connection: local

  roles:

    - { role: download_pypy, tags: download }

# ------------------------------------------------------------------- #
#  Ansible on CoreOS
# ------------------------------------------------------------------- #

- hosts: coreos-cluster
  gather_facts: no

  roles:

    - { role: install_pypy,  tags: pypy  }

- hosts: coreos-cluster
  tasks:

    - debug: msg="running Ansible tasks on all CoreOS hosts"
    
  roles:

    - { role: install_pip,  tags: pip  }

# ------------------------------------------------------------------- #
#  Mesos on CoreOS
# ------------------------------------------------------------------- #

- hosts: zookeepers
  roles:
    - { role: zookeeper,    tags: zookeeper }

- hosts: mesos-masters
  roles:
    - { role: mesos-master, tags: master }

- hosts: mesos-slaves
  roles:
    - { role: mesos-slave,  tags: slave }

# ------------------------------------------------------------------- #
# eof
#