---
# ------------------------------------------------------------------- #
#                     Mesosphere on CoreOS cluster                    #
# ------------------------------------------------------------------- #

- hosts: 127.0.0.1
  connection: local

  roles:

    - { role: download_pypy, tags: download }

- hosts: coreos-cluster
  gather_facts: no

  roles:

    - { role: install_pypy,  tags: install  }

- hosts: coreos-cluster
  tasks:

    - debug: msg="running Ansible tasks on all CoreOS hosts"
    
#    - { role: install_pypy,  tags: install  }
# - hosts: zookeepers
#   roles:

#     - { role: zookeeper, tags: zookeeper, sudo: yes }

# ------------------------------------------------------------------- #
# eof
#