---
# ----------------------------------------------------------------------
#  Case 2: user account exist but has no sudo privileges, use /bin/su
# ----------------------------------------------------------------------

- hosts: hosts_without_user
  remote_user: "{{ nonroot_user }}"
  su: yes

# --------------------------------------------------------
#  Grant sudo priviliges
# --------------------------------------------------------

  roles:

    - { role: sudoers, make_sudo_user: "{{ nonroot_user }}" }

    - passwordless_login
    - sudoers_extra
