---
# ----------------------------------------------------------------------
#  Case 2: user account exist but has no sudo priviliges
# ----------------------------------------------------------------------

- hosts: hosts_without_user
  remote_user: "{{ nonroot_user }}"
  su: yes

# --------------------------------------------------------
#  Grant sudo priviliges
# --------------------------------------------------------

  roles:

    - { role: sudoers, make_sudo_user: "{{ nonroot_user }}", tags: create-sudo-user }
    - passwordless_login
    - sudoers_extra