---
# ----------------------------------------------------------------------
#  Case 1: user account does not exist, ssh directly to root
# ----------------------------------------------------------------------

- hosts: hosts_without_user
  remote_user: root

# --------------------------------------------------------
#  Create user account
# --------------------------------------------------------

  pre_tasks:

    - name: Add non-root user account
      user: name={{ nonroot_user }}
            password={{ nonroot_user_passwd }}
            comment="Non-root account for remote operations"
            update_password="on_create"

# --------------------------------------------------------
#  Grant sudo priviliges
# --------------------------------------------------------

  roles:

    - { role: sudoers, make_sudo_user: "{{ nonroot_user }}" }

    - passwordless_login
    - sudoers_extra
