---
# ----------------------------------------------------------------------
#  Case 1: user account does not exist
# ----------------------------------------------------------------------

- hosts: all
  remote_user: root

# --------------------------------------------------------
#  Create user account
# --------------------------------------------------------

  pre_tasks:

    - name: Add non-root user account
      user: name={{ nonroot_user }} password={{ nonroot_user_passwd }}
            comment="Non-root account for remote operations"

# --------------------------------------------------------
#  Grant priviliges
# --------------------------------------------------------

  roles:

    - passwordless_login
    - sudoers
    - sudoers_extra
