---
# ----------------------------------------------------------------------
#  Case 3: user account exist and has sudo priviliges
# ----------------------------------------------------------------------

# --------------------------------------------------------
#  Miniman install (python, etc)
# --------------------------------------------------------

- hosts: setup_only
  remote_user: "{{ nonroot_user }}"
  gather_facts: no

  roles:
    - { role: min-install, when: do_min_install }

- hosts: setup_only
  remote_user: "{{ nonroot_user }}"

  roles:
    - passwordless_login

- hosts: setup_only
  remote_user: "{{ nonroot_user }}"
  sudo: yes

# --------------------------------------------------------
#  Update sudo setup
# --------------------------------------------------------

  roles:

    - sudoers_extra
    - ssh_setup
    - profile_settings

  tasks:

    - include: tasks/package_install.yml
