---
# ----------------------------------------------------------------------
#  Case 3: user account exist and has sudo priviliges
# ----------------------------------------------------------------------

- hosts: all
  remote_user: "{{ nonroot_user }}"

# --------------------------------------------------------
#  Update sudo setup
# --------------------------------------------------------

  roles:

    - passwordless_login
    - { role: sudoers_extra, sudo: yes }
    - { role: ssh_setup, sudo: yes }
    - profile_settings
    
  tasks:

    - include: tasks/package_install.yml
      sudo: yes
