---
# ----------------------------------------------------------------------
#  Case 3: user account exist and has sudo priviliges
# ----------------------------------------------------------------------

- hosts: all
  remote_user: "{{ nonroot_user }}"

  roles:

    - passwordless_login

- hosts: all
  remote_user: "{{ nonroot_user }}"
  sudo: yes

# --------------------------------------------------------
#  Update sudo setup
# --------------------------------------------------------

  roles:

    - sudoers_extra
    - ssh_setup
    - profile_settings

  tasks:

    - include: tasks/package_install.yml
