---
# ----------------------------------------------------------------------
#  Case 2: user account exist and has sudo priviliges
# ----------------------------------------------------------------------

- hosts: all
  remote_user: "{{ nonroot_user }}"

# --------------------------------------------------------
#  Update sudo priviliges
# --------------------------------------------------------

  roles:

    - passwordless_login
    - { role: sudoers_extra,    sudo: yes }
