---

home_dir:                 "{{ lookup('env', 'HOME') }}"

vms_by_count:             True
vm_count:                 3

# not implemented yet
vms_by_name:              False

local_vm_image_dir:       "{{ playbook_dir }}/vm_image.dir"

vm_image_storage_fs_dir:  "/var/lib/libvirt/images/coreos"
cloud_init_dir:           "{{ vm_image_storage_fs_dir }}"

vm_image_name_prefix:     "vm-coreos"

vm_create_pause:          30      # seconds
vm_startup_pause:         10      # seconds
vm_shutdown_pause:        5       # seconds

# can not use variables with do-until conditional (roll my eyes)
# vm_cmd_retries:           3
# vm_cmd_delay:             1

vm_create_timeout:        90      # seconds
vm_startup_timeout:       60      # seconds

vm_shutdown_timeout_1:    5       # seconds
vm_shutdown_timeout_2:    10      # seconds
vm_shutdown_timeout_3:    15      # seconds
