---

home_dir:                 "{{ lookup('env', 'HOME') }}"

vms_by_count:             True
vm_count:                 3

vms_by_name:              False

local_vm_image_dir:       "{{ playbook_dir }}/vm_image.dir"

vm_image_storage_fs_dir:  /var/lib/libvirt/images/coreos.2

vm_create_pause:          40      # seconds
vm_startup_pause:         20      # seconds
vm_shutdown_pause:        5       # seconds