---

zookeeper_conf_host_dir:          "/home/{{ coreos_username }}/zookeeper/conf"
zookeeper_conf_container_dir:     "/opt/zookeeper/conf"

zookeeper_volume_host_dir:        "/home/{{ coreos_username }}/zookeeper/disk"
zookeeper_volume_container_dir:   "/tmp/zookeeper"

zookeeper_data_dir:               "{{ zookeeper_volume_container_dir }}/data"
zookeeper_log_dir:                "{{ zookeeper_volume_container_dir }}/log"

# the ports for zk servers to communicate with each other
zookeeper_followers_port:   2888
zookeeper_election_port:    3888

# the ports for zk clients to communicate with server
zookeeper_client_port:      2181