---
# Deploy Docker container of Mesos Marathon framework 

# ---------------------------------------------------------------------
#  Service 
# ---------------------------------------------------------------------

- name: Create folder for marathon files
  file: path="{{ item }}" state=directory
  with_items:
    - "{{ marathon_host_dir }}"

- name: Create systemd service file
  template: src={{ item }} dest="{{ marathon_host_dir }}/{{ item | replace('.j2', '') }}"
  with_items:
    - marathon.service.j2
  notify:
    - Copy marathon service systemd file
    - Reload systemd
    - Enable marathon service
    - Restart marathon service

# - name: Remove copy of systemd service file
#   file: name="{{ marathon_host_dir }}/{{ item }}"
#   with_items:
#     - marathon.service

# ---------------------------------------------------------------------
#  Configuration 
# ---------------------------------------------------------------------
