---

docker_compose_download_url:    https://github.com/docker/compose/releases/download
docker_compose_release:         "1.2.0"

docker_compose_command:         "docker-compose"
docker_compose_install_dir:     "/usr/local/bin"

docker_compose_pip_package:     "docker-compose"
